(() => {
  const C = window.SIM_CONFIG, app = document.querySelector('#app');
  const state = { name:'', startedAt:0, elapsed:0, values:{}, interval:null };
  const labels = {pipeline:'Pipeline',stage:'Deal Stage',forecast:'Forecast Category',representative:'Seller Sales Representative',amount:'Amount',products:'Seller Category / Main Products',priority:'Priority',notes:'Deal Notes'};
  const esc = v => String(v ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const opts = (items, first='Select an option') =>
  function welcome(){app.innerHTML=document.querySelector('#welcome-template').innerHTML;const button=document.querySelector('#start');const valid=()=>button.disabled=!(document.querySelector('#participant-name').value.trim()&&document.querySelector('#ready').checked);document.querySelector('#participant-name').oninput=valid;document.querySelector('#ready').onchange=valid;valid();button.onclick=()=>{state.name=document.querySelector('#participant-name').value.trim();scenario()};}
  function scenario(){app.innerHTML=`<section class="screen"><article class="card scenario"><p class="eyebrow">SCENARIO</p><h2>Ready to update the Deal?</h2><p>You have just completed a successful discovery/demo meeting with <strong>Erica Cobian</strong> from <strong>Erica's Tortillas - Test</strong>.</p><p>During the meeting, Erica decided to move forward with the <strong>Seller Direct Program</strong> using the <strong>Growth Subscription</strong> with <strong>Annual Billing</strong>.</p><p>Following the meeting, you have already prepared and sent the customer's formal quotation for review. Your responsibility is now to update the HubSpot Deal so it accurately reflects the current sales status before continuing the sales process.</p><dl class="summary-grid"><div><dt>Company</dt><dd>Erica's Tortillas - Test</dd></div><div><dt>Primary Contact</dt><dd>Erica Cobian</dd></div><div><dt>Program</dt><dd>Seller Direct</dd></div><div><dt>Subscription</dt><dd>Growth Subscription</dd></div><div><dt>Billing</dt><dd>Annual</dd></div><div><dt>Annual Subscription</dt><dd>$9,108.60</dd></div><div><dt>One-Time Onboarding Fee</dt><dd>$1,000.00</dd></div><div><dt>Total Deal Amount</dt><dd>$10,108.60</dd></div></dl><button id="open" class="primary">Open HubSpot Deal</button></article></section>`;document.querySelector('#open').onclick=simulator;}
function position(el, key){
    const [x,y,w,h]=C.overlayPositions[key];
    Object.assign(el.style,{
        left:x+'%',
        top:y+'%',
        width:w+'%',
        height:h+'%'
    });
}
  function field(key, control){const e=document.createElement('label');e.className='field';e.dataset.key=key;position(e,key);e.innerHTML=control+'<small></small>';return e;}
  function simulator(){state.startedAt=Date.now();state.values={pipeline:C.currentValues.pipeline,stage:C.currentValues.stage,forecast:C.currentValues.forecast,representative:'',amount:'',products:'',priority:'',notes:''};app.innerHTML=`<section class="simulator"><header class="sim-top"><strong>Post-Demo HubSpot Simulator</strong><span>Erica's Tortillas - Test</span><span id="timer" class="timer">10:00</span></header><div class="hubspot-canvas" id="canvas"><div class="no-shot" id="no-shot"><div><strong>HubSpot screenshot awaiting asset</strong><small>Add <code>hubspot-screenshot.png</code> to display the supplied Deal interface.</small></div></div></div></section>`;const canvas=document.querySelector('#canvas');const controls={pipeline:`<select>${opts(C.options.pipeline)}</select>`,stage:`<select>${opts(C.options.stage)}</select>`,forecast:`<select>${opts(C.options.forecast)}</select>`,representative:`<select>${opts(C.options.representative)}</select>`,amount:'<input inputmode="decimal" aria-label="Amount">',products:'<input aria-label="Seller Category / Main Products">',priority:`<select>${opts(C.options.priority)}</select>`,notes:'<textarea aria-label="Deal Notes"></textarea>'};Object.entries(controls).forEach(([key,html])=>{const e=field(key,html), c=e.querySelector('input,select,textarea');c.value = state.values[key];c.addEventListener('change',()=>save(key,c.value,e));c.addEventListener('blur',()=>save(key,c.value,e));canvas.append(e)});const submit=document.createElement('button');submit.className='submit-overlay';submit.textContent='Submit';position(submit,'submit');submit.onclick=submitDeal;canvas.append(submit);const img=new Image();img.onload=()=>document.querySelector('#no-shot').remove();img.src='hubspot-screenshot.png';tick();state.interval=setInterval(tick,1000);}
  function save(key,value,el){state.values[key]=value.trim();el.classList.remove('invalid');el.classList.add('saving');el.querySelector('small').textContent='Saving...';setTimeout(()=>{el.querySelector('small').textContent='✓ Changes Saved';setTimeout(()=>el.classList.remove('saving'),900)},380)}
  function tick(){const sec=Math.max(0,C.timerSeconds-Math.floor((Date.now()-state.startedAt)/1000));state.elapsed=Math.floor((Date.now()-state.startedAt)/1000);const el=document.querySelector('#timer');if(el)el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
  function check(){const v=state.values,a=C.correctAnswers;return {pipeline:[v.pipeline===a.pipeline,`Expected ${a.pipeline}`],stage:[v.stage===a.stage,`Expected ${a.stage}`],forecast:[v.forecast===a.forecast,`Expected ${a.forecast}`],representative:[!!v.representative,'Select the Seller Sales Representative'],amount:[v.amount===a.amount,`Expected ${a.amount}. Remember to include the onboarding fee.`],products:[!!v.products,'Enter a Seller Category / Main Products value'],priority:[!!v.priority,'Select a priority'],notes:[a.notesTerms.every(x=>v.notes.toLowerCase().includes(x.toLowerCase())),`Must include “${a.notesTerms[0]}” and “${a.notesTerms[1]}”`]};}
  function submitDeal(){const checks=check(),required=['representative','amount','products','priority','notes'],missing=required.filter(k=>!state.values[k]);if(missing.length){missing.forEach(k=>document.querySelector(`[data-key="${k}"]`)?.classList.add('invalid'));const old=document.querySelector('.banner');if(old)old.remove();const b=document.createElement('div');b.className='banner';b.textContent='Please complete all required properties before submitting this Deal.';document.body.append(b);setTimeout(()=>b.remove(),4000);return;}clearInterval(state.interval);results(checks);}
  const duration=s=>`${Math.floor(s/60)}m ${s%60}s`;
  function results(checks=check()){const passCount=Object.values(checks).filter(r=>r[0]).length,score=Math.round(passCount/Object.keys(checks).length*100),passed=score>=C.scoreToPass;const rows=Object.entries(checks).map(([key,[ok,hint]])=>`<div class="result-row ${ok?'pass':'fail'}"><strong>${ok?'✔':'✖'} ${labels[key]}</strong><small>${ok?esc(state.values[key]):`Entered: ${esc(state.values[key]||'—')} · ${esc(hint)}`}</small></div>`).join('');app.innerHTML=`<section class="screen results"><article class="card"><p class="eyebrow">TRAINING RESULTS</p><h2>${passed?'Great work — Deal submitted':'Submission complete — coaching recommended'}</h2><div class="score"><b>${score}%</b><div><strong>${passed?'Passed':'Needs Coaching'}</strong><br>${esc(state.name)} · ${new Date().toLocaleDateString()} · ${duration(state.elapsed)}</div></div><div class="validation">${rows}</div><div class="actions"><button class="primary" id="download">Download Training Report</button><button class="secondary" id="sharepoint">Open SharePoint Submission Folder</button></div></article></section>`;document.querySelector('#download').onclick=report;document.querySelector('#sharepoint').onclick=()=>window.open(C.sharePointUrl,'_blank','noopener');}
  function report(){const checks=check(),score=Math.round(Object.values(checks).filter(r=>r[0]).length/8*100);const responses=Object.keys(labels).map(k=>`<tr><td>${labels[k]}</td><td>${esc(state.values[k]||'—')}</td><td>${checks[k][0]?'Pass':'Needs coaching'}</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><title>Training Report - ${esc(state.name)}</title><style>body{font:11pt Arial;color:#172d3e;margin:34px}h1{color:#173047;margin-bottom:4px}table{width:100%;border-collapse:collapse;margin:18px 0}th,td{border:1px solid #bdcbd5;padding:8px;text-align:left}th{background:#eaf4ff}.box{padding:14px;background:#f4f7fa;margin:15px 0}.review{height:120px;border:1px solid #aaa;padding:8px}@media print{body{margin:15mm}}</style></head><body><h1>Post-Demo HubSpot Simulator</h1><p>Training Report</p><div class="box"><strong>Participant:</strong> ${esc(state.name)}<br><strong>Date:</strong> ${new Date().toLocaleDateString()}<br><strong>Completion Time:</strong> ${duration(state.elapsed)}<br><strong>Overall Score:</strong> ${score}%</div><h2>Scenario Summary</h2><p>Erica's Tortillas - Test — successful discovery/demo. Seller Direct program, Growth Subscription, Annual Billing; quoted amount $10,108.60.</p><h2>Participant Responses & Validation Results</h2><table><tr><th>Property</th><th>Response</th><th>Result</th></tr>${responses}</table><h2>Manager Review</h2><div class="review">Manager comments:</div><script>window.onload=()=>window.print()<\/script></body></html>`;const win=window.open('','_blank');if(!win){alert('Please allow pop-ups to download the printable report.');return;}win.document.write(html);win.document.close();}
  welcome();
})();
